module.exports =
  AngelicAvenger: require './paragon_paths/angelic_avenger'
  AstralWeapon  : require './paragon_paths/astral_weapon'
  DivineOracle  : require './paragon_paths/divine_oracle'
  IronVanguard  : require './paragon_paths/iron_vanguard'
  Kensei        : require './paragon_paths/kensei'
  PitFighter    : require './paragon_paths/pit_fighter'
  RadiantServant: require './paragon_paths/radiant_servant'
  Swordmaster   : require './paragon_paths/swordmaster'
  Warpriest     : require './paragon_paths/warpriest'
