module.exports =
  AngelicAvenger   : require './paragon_paths/angelic_avenger'
  AstralWeapon     : require './paragon_paths/astral_weapon'
  BattlefieldArcher: require './paragon_paths/battlefield_archer'
  BeastStalker     : require './paragon_paths/beast_stalker'
  CatBurglar       : require './paragon_paths/cat_burglar'
  ChampionOfOrder  : require './paragon_paths/champion_of_order'
  Daggermaster     : require './paragon_paths/daggermaster'
  DivineOracle     : require './paragon_paths/divine_oracle'
  Doomsayer        : require './paragon_paths/doomsayer'
  Feytouched       : require './paragon_paths/feytouched'
  Hospitaler       : require './paragon_paths/hospitaler'
  IronVanguard     : require './paragon_paths/iron_vanguard'
  Justiciar        : require './paragon_paths/justiciar'
  Kensei           : require './paragon_paths/kensei'
  LifeStealer      : require './paragon_paths/life_stealer'
  MasterInfiltrator: require './paragon_paths/master_infiltrator'
  Pathfinder       : require './paragon_paths/pathfinder'
  PitFighter       : require './paragon_paths/pit_fighter'
  RadiantServant   : require './paragon_paths/radiant_servant'
  ShadowAssassin   : require './paragon_paths/shadow_assassin'
  Stormwarden      : require './paragon_paths/stormwarden'
  Swordmaster      : require './paragon_paths/swordmaster'
  Warpriest        : require './paragon_paths/warpriest'
