module.exports =
  AngelicAvenger : require './paragon_paths/angelic_avenger'
  AstralWeapon   : require './paragon_paths/astral_weapon'
  ChampionOfOrder: require './paragon_paths/champion_of_order'
  DivineOracle   : require './paragon_paths/divine_oracle'
  Hospitaler     : require './paragon_paths/hospitaler'
  IronVanguard   : require './paragon_paths/iron_vanguard'
  Justiciar      : require './paragon_paths/justiciar'
  Kensei         : require './paragon_paths/kensei'
  PitFighter     : require './paragon_paths/pit_fighter'
  RadiantServant : require './paragon_paths/radiant_servant'
  Swordmaster    : require './paragon_paths/swordmaster'
  Warpriest      : require './paragon_paths/warpriest'
